In [13]:
import pandas as pd
import numpy as np
from ast import literal_eval

In [14]:
from codetotitle import CodetoTitle 

In [15]:
movies = pd.read_csv('final_reple.csv', encoding='utf-8', names=['code', 'reple'])
movies = movies.loc[:, ['code','reple']]


In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer
# ngram_range=(1, 2) 는 단어를 1개 혹은 2개 연속으로 보겠다
tfidf_vec = TfidfVectorizer(ngram_range=(1, 2))
tfidf_matrix = tfidf_vec.fit_transform(movies['reple'])
print(tfidf_vec.vocabulary_.items())
# 4803은 영화의 개수, 276은 단어의 개수 -> 하나의 영화를 276개 열을 가진 벡터로 표현
print(tfidf_matrix.shape)

# action adventure fantasy
# adventure fantasy
# adventure
# fantasy

9636), ('전곡이', 95161), ('시작하는', 61626), ('주제가만', 100813), ('2017년', 1016), ('실사영화와', 62473), ('비교해보면', 51864), ('애니에서는', 69579), ('표정과', 113220), ('가스톤의', 4946), ('과장된', 11516), ('마초스러움', 35356), ('부드러운', 50567), ('눈동자를', 23730), ('3말이', 1792), ('명작기억은', 39407), ('가물가물', 4825), ('해져도', 116972), ('간직될', 5708), ('로미오와', 33785), ('줄리엣', 101273), ('연인', 75465), ('戀人', 120852), ('사랑이야기의', 53807), ('必要韓紙', 4490), ('미녀여야만', 42819), ('안좋게', 67637), ('시선도', 61464), ('어릴때부터', 71380), ('이작품', 86801), ('부풀어오르는', 51082), ('같달까', 7668), ('ㅠㅠ추억으로', 4322), ('간직되신', 5706), ('아실거에요', 65825), ('황홀다는느낌은처음인듯ㅠㅠ야수가', 119164), ('변했을', 45900), ('취향인데', 107762), ('진리다디즈니', 103017), ('외모로는', 81335), ('섹시하고', 57449), ('다함', 26080), ('옛말엔', 79471), ('유치하지않을수가없었는데', 83899), ('이제와', 86964), ('아름다울수가', 65040), ('ㅠㅠ디즈니', 4217), ('애니보면서', 69567), ('꺽꺽', 17438), ('ㅠㅠ슬픈장면이', 4254), ('난다이건', 19811), ('영화화해선', 79020), ('발끝도', 44481), ('못미침', 40955), ('과거나', 11450), ('현대에서도', 118074), ('인정되는', 87744), ('문화재급임', 42161), ('뽑아

In [16]:
from sklearn.metrics.pairwise import cosine_similarity

genres_similarity = cosine_similarity(tfidf_matrix, tfidf_matrix)
print(genres_similarity)

similar_index = np.argsort(-genres_similarity)
print(similar_index)

[[1.         0.04891653 0.05382406 ... 0.0389569  0.03217762 0.05117635]
 [0.04891653 1.         0.03798851 ... 0.03124697 0.02599475 0.02178397]
 [0.05382406 0.03798851 1.         ... 0.02414833 0.03008257 0.02966889]
 ...
 [0.0389569  0.03124697 0.02414833 ... 1.         0.0304947  0.02342598]
 [0.03217762 0.02599475 0.03008257 ... 0.0304947  1.         0.02748739]
 [0.05117635 0.02178397 0.02966889 ... 0.02342598 0.02748739 1.        ]]
[[ 0 27 38 ... 26 25 68]
 [ 1  0 66 ... 24 41 34]
 [ 2  0 38 ... 28 36 68]
 ...
 [79 66 63 ... 11 41 30]
 [80 65 73 ... 41 68 25]
 [81 33 12 ... 24 25 44]]


In [17]:
input_movie = input()
input_movie = input()
input_movie = input()

movie_index = movies[movies['code']==int(input_movie)].index.values
#print(movie_index)
similar_movies = similar_index[movie_index, 1:4]
#print(similar_movies)
# 인덱스로 사용하기 위해서는 1차원으로 변형해줘야하기 때문
similar_movies_index = similar_movies.reshape(-1)
#print(similar_movies_index)
#print(movies.iloc[similar_movies_index])

info = movies.iloc[similar_movies_index]
#print(info)
#print(info['code'])
code_info = list(np.array(info['code'].tolist()))
#print(code_info)

for i in code_info:
    CodetoTitle(i)

피터와 드래곤
알라딘
애프터 어스
