In [3]:
import pandas as pd
import numpy as np
from ast import literal_eval

In [4]:
from codetotitle import CodetoTitle 

In [7]:
movies = pd.read_csv('final_plot.csv', encoding='utf-8', names=['code', 'plot'])
movies = movies.loc[:, ['code','plot']]


In [21]:
tfidf

NameError: name 'tfidf' is not defined

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
# ngram_range=(1, 2) 는 단어를 1개 혹은 2개 연속으로 보겠다
tfidf_vec = TfidfVectorizer(ngram_range=(1, 2))
tfidf_matrix = tfidf_vec.fit_transform(movies['plot'])
print(tfidf_vec.vocabulary_.items())
print(tfidf_matrix.shape)


, 21436), ('얘기하는', 67706), ('콜튼', 103093), ('천국에서의', 98184), ('상세하게', 51386), ('털어놓는', 104800), ('콜튼의', 103099), ('들썩이기', 28082), ('소동에', 55762), ('조용했던', 92752), ('천국을', 98190), ('콜튼으로', 103095), ('토드와', 105076), ('천국은', 98188), ('진짜였을까', 96178), ('조용한 시골', 92750), ('시골 마을의', 60536), ('마을의 토드는', 33460), ('토드는 마을', 105075), ('마을 주민들을', 33425), ('주민들을 도우며', 93694), ('도우며 성실하게', 25602), ('성실하게 살고', 54183), ('있는 가정의', 84503), ('가정의 가장이다', 4019), ('가장이다 그러던', 4005), ('어느 그의', 67724), ('그의 네살배기', 14943), ('네살배기 아들', 19624), ('아들 콜튼이', 63891), ('콜튼이 위급한', 103103), ('위급한 상태에', 77704), ('상태에 빠지게', 51576), ('빠지게 되고', 49084), ('되고 결국', 26768), ('결국 손을', 9100), ('손을 없을', 56591), ('없을 지경에까지', 69416), ('지경에까지 이르게', 94922), ('그러나 가족과', 14238), ('가족과 주민들의', 4097), ('주민들의 간절한', 93697), ('간절한 기도', 4698), ('기도 끝에', 15822), ('끝에 어린', 17760), ('어린 콜튼은', 68168), ('콜튼은 생사의', 103098), ('생사의 갈림길에서', 52494), ('갈림길에서 기적적으로', 4790), ('기적적으로 살아나게', 16562), ('살아나게 된다', 50966), ('이후 자신이', 82442), ('자신이 천국에', 86408)

In [9]:
from sklearn.metrics.pairwise import cosine_similarity

genres_similarity = cosine_similarity(tfidf_matrix, tfidf_matrix)
print(genres_similarity)

similar_index = np.argsort(-genres_similarity)
print(similar_index)

[[1.         0.02273681 0.02634753 ... 0.00476316 0.00201344 0.00388201]
 [0.02273681 1.         0.02783016 ... 0.00747722 0.00325252 0.00564527]
 [0.02634753 0.02783016 1.         ... 0.00830409 0.00139802 0.00666348]
 ...
 [0.00476316 0.00747722 0.00830409 ... 1.         0.         0.00718531]
 [0.00201344 0.00325252 0.00139802 ... 0.         1.         0.00542217]
 [0.00388201 0.00564527 0.00666348 ... 0.00718531 0.00542217 1.        ]]
[[ 0 19 22 ... 88 83 58]
 [ 1 80 27 ... 85 70 58]
 [ 2 29 25 ... 70 88 75]
 ...
 [87 55  9 ... 57 74 68]
 [88 47 55 ... 57 77 74]
 [89 60  3 ... 85 57 73]]


In [24]:
input_movie = input()
input_movie = input()
input_movie = input()

movie_index = movies[movies['code']==int(input_movie)].index.values
#print(movie_index)
similar_movies = similar_index[movie_index, 1:4]
#print(similar_movies)
# 인덱스로 사용하기 위해서는 1차원으로 변형해줘야하기 때문
similar_movies_index = similar_movies.reshape(-1)
#print(similar_movies_index)
#print(movies.iloc[similar_movies_index])

info = movies.iloc[similar_movies_index]
#print(info)
#print(info['code'])
code_info = list(np.array(info['code'].tolist()))
#print(code_info)

for i in code_info:
    CodetoTitle(i)



투건스
마이 리틀 자이언트
어메이징 스파이더맨 2
